export type RomanianLocation = {
  city: string;
  county: string;
};

export const romanianLocations: RomanianLocation[] = [
  { city: "Abrud", county: "Alba" },
  { city: "Adjud", county: "Vrancea" },
  { city: "Agnita", county: "Sibiu" },
  { city: "Aiud", county: "Alba" },
  { city: "Alba Iulia", county: "Alba" },
  { city: "Aleșd", county: "Bihor" },
  { city: "Alexandria", county: "Teleorman" },
  { city: "Amara", county: "Ialomița" },
  { city: "Anina", county: "Caraș-Severin" },
  { city: "Aninoasa", county: "Hunedoara" },
  { city: "Arad", county: "Arad" },
  { city: "Ardud", county: "Satu Mare" },
  { city: "Avrig", county: "Sibiu" },
  { city: "Azuga", county: "Prahova" },
  { city: "Babadag", county: "Tulcea" },
  { city: "Bacău", county: "Bacău" },
  { city: "Baia de Aramă", county: "Mehedinți" },
  { city: "Baia de Arieș", county: "Alba" },
  { city: "Baia Mare", county: "Maramureș" },
  { city: "Baia Sprie", county: "Maramureș" },
  { city: "Balș", county: "Olt" },
  { city: "Baraolt", county: "Covasna" },
  { city: "Băbeni", county: "Vâlcea" },
  { city: "Băicoi", county: "Prahova" },
  { city: "Băile Govora", county: "Vâlcea" },
  { city: "Băile Herculane", county: "Caraș-Severin" },
  { city: "Băile Olănești", county: "Vâlcea" },
  { city: "Băile Tușnad", county: "Harghita" },
  { city: "Băilești", county: "Dolj" },
  { city: "Bălan", county: "Harghita" },
  { city: "Bălcești", county: "Vâlcea" },
  { city: "Bârlad", county: "Vaslui" },
  { city: "Bechet", county: "Dolj" },
  { city: "Beclean", county: "Bistrița-Năsăud" },
  { city: "Beiuș", county: "Bihor" },
  { city: "Berbești", county: "Vâlcea" },
  { city: "Berești", county: "Galați" },
  { city: "Bicaz", county: "Neamț" },
  { city: "Bistrița", county: "Bistrița-Năsăud" },
  { city: "Blaj", county: "Alba" },
  { city: "Bocșa", county: "Caraș-Severin" },
  { city: "Boldești-Scăeni", county: "Prahova" },
  { city: "Bolintin-Vale", county: "Giurgiu" },
  { city: "Borsec", county: "Harghita" },
  { city: "Borșa", county: "Maramureș" },
  { city: "Botoșani", county: "Botoșani" },
  { city: "Brad", county: "Hunedoara" },
  { city: "Bragadiru", county: "Ilfov" },
  { city: "Brașov", county: "Brașov" },
  { city: "Brăila", county: "Brăila" },
  { city: "Breaza", county: "Prahova" },
  { city: "Brezoi", county: "Vâlcea" },
  { city: "Broșteni", county: "Suceava" },
  { city: "Bucecea", county: "Botoșani" },
  { city: "București", county: "București" },
  { city: "Budești", county: "Călărași" },
  { city: "Buftea", county: "Ilfov" },
  { city: "Buhuși", county: "Bacău" },
  { city: "Bumbești-Jiu", county: "Gorj" },
  { city: "Bușteni", county: "Prahova" },
  { city: "Buzău", county: "Buzău" },
  { city: "Buziaș", county: "Timiș" },
  { city: "Cajvana", county: "Suceava" },
  { city: "Calafat", county: "Dolj" },
  { city: "Caracal", county: "Olt" },
  { city: "Caransebeș", county: "Caraș-Severin" },
  { city: "Carei", county: "Satu Mare" },
  { city: "Cavnic", county: "Maramureș" },
  { city: "Călan", county: "Hunedoara" },
  { city: "Călărași", county: "Călărași" },
  { city: "Călimănești", county: "Vâlcea" },
  { city: "Căzănești", county: "Ialomița" },
  { city: "Câmpeni", county: "Alba" },
  { city: "Câmpia Turzii", county: "Cluj" },
  { city: "Câmpina", county: "Prahova" },
  { city: "Câmpulung", county: "Argeș" },
  { city: "Câmpulung Moldovenesc", county: "Suceava" },
  { city: "Cehu Silvaniei", county: "Sălaj" },
  { city: "Cernavodă", county: "Constanța" },
  { city: "Chișineu-Criș", county: "Arad" },
  { city: "Chitila", county: "Ilfov" },
  { city: "Ciacova", county: "Timiș" },
  { city: "Cisnădie", county: "Sibiu" },
  { city: "Cluj-Napoca", county: "Cluj" },
  { city: "Codlea", county: "Brașov" },
  { city: "Comarnic", county: "Prahova" },
  { city: "Comănești", county: "Bacău" },
  { city: "Constanța", county: "Constanța" },
  { city: "Copșa Mică", county: "Sibiu" },
  { city: "Corabia", county: "Olt" },
  { city: "Costești", county: "Argeș" },
  { city: "Covasna", county: "Covasna" },
  { city: "Craiova", county: "Dolj" },
  { city: "Cristuru Secuiesc", county: "Harghita" },
  { city: "Cugir", county: "Alba" },
  { city: "Curtea de Argeș", county: "Argeș" },
  { city: "Curtici", county: "Arad" },
  { city: "Darabani", county: "Botoșani" },
  { city: "Dăbuleni", county: "Dolj" },
  { city: "Dărmănești", county: "Bacău" },
  { city: "Dej", county: "Cluj" },
  { city: "Deta", county: "Timiș" },
  { city: "Deva", county: "Hunedoara" },
  { city: "Dolhasca", county: "Suceava" },
  { city: "Dorohoi", county: "Botoșani" },
  { city: "Dragomirești", county: "Maramureș" },
  { city: "Drăgănești-Olt", county: "Olt" },
  { city: "Drăgășani", county: "Vâlcea" },
  { city: "Drobeta-Turnu Severin", county: "Mehedinți" },
  { city: "Dumbrăveni", county: "Sibiu" },
  { city: "Eforie", county: "Constanța" },
  { city: "Făgăraș", county: "Brașov" },
  { city: "Făget", county: "Timiș" },
  { city: "Fălticeni", county: "Suceava" },
  { city: "Făurei", county: "Brăila" },
  { city: "Fetești", county: "Ialomița" },
  { city: "Fieni", county: "Dâmbovița" },
  { city: "Fierbinți-Târg", county: "Ialomița" },
  { city: "Filiași", county: "Dolj" },
  { city: "Flămânzi", county: "Botoșani" },
  { city: "Focșani", county: "Vrancea" },
  { city: "Frasin", county: "Suceava" },
  { city: "Fundulea", county: "Călărași" },
  { city: "Galați", county: "Galați" },
  { city: "Găești", county: "Dâmbovița" },
  { city: "Gătaia", county: "Timiș" },
  { city: "Geoagiu", county: "Hunedoara" },
  { city: "Gheorgheni", county: "Harghita" },
  { city: "Gherla", county: "Cluj" },
  { city: "Ghimbav", county: "Brașov" },
  { city: "Giurgiu", county: "Giurgiu" },
  { city: "Gura Humorului", county: "Suceava" },
  { city: "Hațeg", county: "Hunedoara" },
  { city: "Hârlău", county: "Iași" },
  { city: "Hârșova", county: "Constanța" },
  { city: "Horezu", county: "Vâlcea" },
  { city: "Huedin", county: "Cluj" },
  { city: "Hunedoara", county: "Hunedoara" },
  { city: "Huși", county: "Vaslui" },
  { city: "Ianca", county: "Brăila" },
  { city: "Iași", county: "Iași" },
  { city: "Iernut", county: "Mureș" },
  { city: "Ineu", county: "Arad" },
  { city: "Isaccea", county: "Tulcea" },
  { city: "Însurăței", county: "Brăila" },
  { city: "Întorsura Buzăului", county: "Covasna" },
  { city: "Jibou", county: "Sălaj" },
  { city: "Jimbolia", county: "Timiș" },
  { city: "Lehliu Gară", county: "Călărași" },
  { city: "Lipova", county: "Arad" },
  { city: "Liteni", county: "Suceava" },
  { city: "Livada", county: "Satu Mare" },
  { city: "Luduș", county: "Mureș" },
  { city: "Lugoj", county: "Timiș" },
  { city: "Lupeni", county: "Hunedoara" },
  { city: "Mangalia", county: "Constanța" },
  { city: "Marghita", county: "Bihor" },
  { city: "Măcin", county: "Tulcea" },
  { city: "Măgurele", county: "Ilfov" },
  { city: "Mărășești", county: "Vrancea" },
  { city: "Medgidia", county: "Constanța" },
  { city: "Mediaș", county: "Sibiu" },
  { city: "Miercurea Ciuc", county: "Harghita" },
  { city: "Miercurea Nirajului", county: "Mureș" },
  { city: "Miercurea Sibiului", county: "Sibiu" },
  { city: "Mihăilești", county: "Giurgiu" },
  { city: "Milișăuți", county: "Suceava" },
  { city: "Mioveni", county: "Argeș" },
  { city: "Mizil", county: "Prahova" },
  { city: "Moinești", county: "Bacău" },
  { city: "Moldova Nouă", county: "Caraș-Severin" },
  { city: "Moreni", county: "Dâmbovița" },
  { city: "Motru", county: "Gorj" },
  { city: "Murfatlar", county: "Constanța" },
  { city: "Murgeni", county: "Vaslui" },
  { city: "Nădlac", county: "Arad" },
  { city: "Năsăud", county: "Bistrița-Năsăud" },
  { city: "Năvodari", county: "Constanța" },
  { city: "Negrești", county: "Vaslui" },
  { city: "Negrești-Oaș", county: "Satu Mare" },
  { city: "Negru Vodă", county: "Constanța" },
  { city: "Nehoiu", county: "Buzău" },
  { city: "Novaci", county: "Gorj" },
  { city: "Nucet", county: "Bihor" },
  { city: "Ocna Mureș", county: "Alba" },
  { city: "Ocna Sibiului", county: "Sibiu" },
  { city: "Ocnele Mari", county: "Vâlcea" },
  { city: "Odobești", county: "Vrancea" },
  { city: "Odorheiu Secuiesc", county: "Harghita" },
  { city: "Oltenița", county: "Călărași" },
  { city: "Onești", county: "Bacău" },
  { city: "Oradea", county: "Bihor" },
  { city: "Oravița", county: "Caraș-Severin" },
  { city: "Orăștie", county: "Hunedoara" },
  { city: "Orșova", county: "Mehedinți" },
  { city: "Otopeni", county: "Ilfov" },
  { city: "Oțelu Roșu", county: "Caraș-Severin" },
  { city: "Ovidiu", county: "Constanța" },
  { city: "Panciu", county: "Vrancea" },
  { city: "Pantelimon", county: "Ilfov" },
  { city: "Pașcani", county: "Iași" },
  { city: "Pătârlagele", county: "Buzău" },
  { city: "Pâncota", county: "Arad" },
  { city: "Pecica", county: "Arad" },
  { city: "Petrila", county: "Hunedoara" },
  { city: "Petroșani", county: "Hunedoara" },
  { city: "Piatra Neamț", county: "Neamț" },
  { city: "Piatra-Olt", county: "Olt" },
  { city: "Pitești", county: "Argeș" },
  { city: "Ploiești", county: "Prahova" },
  { city: "Plopeni", county: "Prahova" },
  { city: "Podu Iloaiei", county: "Iași" },
  { city: "Pogoanele", county: "Buzău" },
  { city: "Popești-Leordeni", county: "Ilfov" },
  { city: "Potcoava", county: "Olt" },
  { city: "Predeal", county: "Brașov" },
  { city: "Pucioasa", county: "Dâmbovița" },
  { city: "Răcari", county: "Dâmbovița" },
  { city: "Rădăuți", county: "Suceava" },
  { city: "Râmnicu Sărat", county: "Buzău" },
  { city: "Râmnicu Vâlcea", county: "Vâlcea" },
  { city: "Râșnov", county: "Brașov" },
  { city: "Recaș", county: "Timiș" },
  { city: "Reghin", county: "Mureș" },
  { city: "Reșița", county: "Caraș-Severin" },
  { city: "Roman", county: "Neamț" },
  { city: "Roșiorii de Vede", county: "Teleorman" },
  { city: "Rovinari", county: "Gorj" },
  { city: "Roznov", county: "Neamț" },
  { city: "Rupea", county: "Brașov" },
  { city: "Salcea", county: "Suceava" },
  { city: "Salonta", county: "Bihor" },
  { city: "Satu Mare", county: "Satu Mare" },
  { city: "Săcele", county: "Brașov" },
  { city: "Săcueni", county: "Bihor" },
  { city: "Săliște", county: "Sibiu" },
  { city: "Săliștea de Sus", county: "Maramureș" },
  { city: "Sărmașu", county: "Mureș" },
  { city: "Săveni", county: "Botoșani" },
  { city: "Sângeorgiu de Pădure", county: "Mureș" },
  { city: "Sângeorz-Băi", county: "Bistrița-Năsăud" },
  { city: "Sânnicolau Mare", county: "Timiș" },
  { city: "Sântana", county: "Arad" },
  { city: "Scornicești", county: "Olt" },
  { city: "Sebeș", county: "Alba" },
  { city: "Sebiș", county: "Arad" },
  { city: "Segarcea", county: "Dolj" },
  { city: "Seini", county: "Maramureș" },
  { city: "Sfântu Gheorghe", county: "Covasna" },
  { city: "Sibiu", county: "Sibiu" },
  { city: "Sighetu Marmației", county: "Maramureș" },
  { city: "Sighișoara", county: "Mureș" },
  { city: "Simeria", county: "Hunedoara" },
  { city: "Sinaia", county: "Prahova" },
  { city: "Siret", county: "Suceava" },
  { city: "Slatina", county: "Olt" },
  { city: "Slănic", county: "Prahova" },
  { city: "Slănic Moldova", county: "Bacău" },
  { city: "Slobozia", county: "Ialomița" },
  { city: "Solca", county: "Suceava" },
  { city: "Sovata", county: "Mureș" },
  { city: "Strehaia", county: "Mehedinți" },
  { city: "Suceava", county: "Suceava" },
  { city: "Sulina", county: "Tulcea" },
  { city: "Șimleu Silvaniei", county: "Sălaj" },
  { city: "Șomcuta Mare", county: "Maramureș" },
  { city: "Ștefănești", county: "Argeș" },
  { city: "Ștefănești", county: "Botoșani" },
  { city: "Ștei", county: "Bihor" },
  { city: "Tălmaciu", county: "Sibiu" },
  { city: "Tășnad", county: "Satu Mare" },
  { city: "Tăuții-Măgherăuș", county: "Maramureș" },
  { city: "Târgoviște", county: "Dâmbovița" },
  { city: "Târgu Bujor", county: "Galați" },
  { city: "Târgu Cărbunești", county: "Gorj" },
  { city: "Târgu Frumos", county: "Iași" },
  { city: "Târgu Jiu", county: "Gorj" },
  { city: "Târgu Lăpuș", county: "Maramureș" },
  { city: "Târgu Mureș", county: "Mureș" },
  { city: "Târgu Neamț", county: "Neamț" },
  { city: "Târgu Ocna", county: "Bacău" },
  { city: "Târgu Secuiesc", county: "Covasna" },
  { city: "Târnăveni", county: "Mureș" },
  { city: "Techirghiol", county: "Constanța" },
  { city: "Tecuci", county: "Galați" },
  { city: "Teiuș", county: "Alba" },
  { city: "Timișoara", county: "Timiș" },
  { city: "Tismana", county: "Gorj" },
  { city: "Titu", county: "Dâmbovița" },
  { city: "Toplița", county: "Harghita" },
  { city: "Topoloveni", county: "Argeș" },
  { city: "Tulcea", county: "Tulcea" },
  { city: "Turceni", county: "Gorj" },
  { city: "Turda", county: "Cluj" },
  { city: "Turnu Măgurele", county: "Teleorman" },
  { city: "Țăndărei", county: "Ialomița" },
  { city: "Țicleni", county: "Gorj" },
  { city: "Ulmeni", county: "Maramureș" },
  { city: "Ungheni", county: "Mureș" },
  { city: "Uricani", county: "Hunedoara" },
  { city: "Urlați", county: "Prahova" },
  { city: "Urziceni", county: "Ialomița" },
  { city: "Valea lui Mihai", county: "Bihor" },
  { city: "Vaslui", county: "Vaslui" },
  { city: "Vașcău", county: "Bihor" },
  { city: "Vatra Dornei", county: "Suceava" },
  { city: "Vălenii de Munte", county: "Prahova" },
  { city: "Vânju Mare", county: "Mehedinți" },
  { city: "Vicovu de Sus", county: "Suceava" },
  { city: "Victoria", county: "Brașov" },
  { city: "Videle", county: "Teleorman" },
  { city: "Vișeu de Sus", county: "Maramureș" },
  { city: "Vlăhița", county: "Harghita" },
  { city: "Voluntari", county: "Ilfov" },
  { city: "Vulcan", county: "Hunedoara" },
  { city: "Zalău", county: "Sălaj" },
  { city: "Zărnești", county: "Brașov" },
  { city: "Zimnicea", county: "Teleorman" },
  { city: "Zlatna", county: "Alba" },
];
