import {
  Baby,
  Bike,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  Car,
  Handshake,
  Home,
  Laptop,
  Palette,
  PawPrint,
  Plane,
  Shirt,
  Sofa,
  Sparkles,
  ThumbsUp,
  Tractor,
  Wrench,
} from "lucide-react";
import type { ComponentType } from "react";

import type { CategoryIconName } from "@/lib/mock-data";

export const categoryIcons = {
  laptop: Laptop,
  car: Car,
  home: Home,
  sofa: Sofa,
  shirt: Shirt,
  bike: Bike,
  baby: Baby,
  wrench: Wrench,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  calendar: CalendarDays,
  palette: Palette,
  paw: PawPrint,
  plane: Plane,
  tractor: Tractor,
  sparkles: Sparkles,
  handshake: Handshake,
  thumbsUp: ThumbsUp,
} satisfies Record<CategoryIconName, ComponentType<{ className?: string }>>;
